package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/graph/model"
	"github.com/sodium-labs/hrms/backend/internal/modules/department"
)

// CreateDepartment is the resolver for the createDepartment field.
func (r *mutationResolver) CreateDepartment(ctx context.Context, input model.CreateDepartmentInput) (*model.Department, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	parentID, err := pIDFromStr(input.ParentID)
	if err != nil {
		return nil, err
	}
	d, err := r.DeptSvc.Create(ctx, tid, department.CreateInput{
		Name:     input.Name,
		Code:     input.Code,
		ParentID: parentID,
	})
	if err != nil {
		return nil, err
	}
	return toGQLDepartment(d), nil
}

// UpdateDepartment is the resolver for the updateDepartment field.
func (r *mutationResolver) UpdateDepartment(ctx context.Context, id string, input model.UpdateDepartmentInput) (*model.Department, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	dID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	parentID, err := pIDFromStr(input.ParentID)
	if err != nil {
		return nil, err
	}
	d, err := r.DeptSvc.Update(ctx, tid, dID, department.UpdateInput{
		Name:     input.Name,
		Code:     input.Code,
		ParentID: parentID,
		Status:   input.Status,
	})
	if err != nil {
		return nil, err
	}
	return toGQLDepartment(d), nil
}

// DeleteDepartment is the resolver for the deleteDepartment field.
func (r *mutationResolver) DeleteDepartment(ctx context.Context, id string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	dID, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.DeptSvc.Delete(ctx, tid, dID); err != nil {
		return false, err
	}
	return true, nil
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.DeptSvc.List(ctx, tid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Department, len(items))
	for i := range items {
		out[i] = toGQLDepartment(&items[i])
	}
	return out, nil
}

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context, id string) (*model.Department, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	dID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	d, err := r.DeptSvc.Get(ctx, tid, dID)
	if err != nil {
		return nil, err
	}
	return toGQLDepartment(d), nil
}
