package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/graph/model"
	"github.com/sodium-labs/hrms/backend/internal/modules/designation"
)

// CreateDesignation is the resolver for the createDesignation field.
func (r *mutationResolver) CreateDesignation(ctx context.Context, input model.CreateDesignationInput) (*model.Designation, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	deptID, err := pIDFromStr(input.DepartmentID)
	if err != nil {
		return nil, err
	}
	d, err := r.DesigSvc.Create(ctx, tid, designation.CreateInput{
		Title:        input.Title,
		Level:        intToInt32Ptr(input.Level),
		DepartmentID: deptID,
	})
	if err != nil {
		return nil, err
	}
	return toGQLDesignation(d), nil
}

// UpdateDesignation is the resolver for the updateDesignation field.
func (r *mutationResolver) UpdateDesignation(ctx context.Context, id string, input model.UpdateDesignationInput) (*model.Designation, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	dID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	deptID, err := pIDFromStr(input.DepartmentID)
	if err != nil {
		return nil, err
	}
	d, err := r.DesigSvc.Update(ctx, tid, dID, designation.UpdateInput{
		Title:        input.Title,
		Level:        intToInt32Ptr(input.Level),
		DepartmentID: deptID,
		Status:       input.Status,
	})
	if err != nil {
		return nil, err
	}
	return toGQLDesignation(d), nil
}

// DeleteDesignation is the resolver for the deleteDesignation field.
func (r *mutationResolver) DeleteDesignation(ctx context.Context, id string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	dID, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.DesigSvc.Delete(ctx, tid, dID); err != nil {
		return false, err
	}
	return true, nil
}

// Designations is the resolver for the designations field.
func (r *queryResolver) Designations(ctx context.Context) ([]*model.Designation, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.DesigSvc.List(ctx, tid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Designation, len(items))
	for i := range items {
		out[i] = toGQLDesignation(&items[i])
	}
	return out, nil
}

// Designation is the resolver for the designation field.
func (r *queryResolver) Designation(ctx context.Context, id string) (*model.Designation, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	dID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	d, err := r.DesigSvc.Get(ctx, tid, dID)
	if err != nil {
		return nil, err
	}
	return toGQLDesignation(d), nil
}
