package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/graph/model"
	"github.com/sodium-labs/hrms/backend/internal/modules/employee"
)

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.CreateEmployeeInput) (*model.Employee, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	in, err := toCreateEmployeeInput(input)
	if err != nil {
		return nil, err
	}
	e, err := r.EmpSvc.Create(ctx, tid, in)
	if err != nil {
		return nil, err
	}
	return toGQLEmployee(e), nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, id string, input model.UpdateEmployeeInput) (*model.Employee, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	eID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	in, err := toUpdateEmployeeInput(input)
	if err != nil {
		return nil, err
	}
	e, err := r.EmpSvc.Update(ctx, tid, eID, in)
	if err != nil {
		return nil, err
	}
	return toGQLEmployee(e), nil
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *mutationResolver) DeleteEmployee(ctx context.Context, id string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	eID, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.EmpSvc.Delete(ctx, tid, eID); err != nil {
		return false, err
	}
	return true, nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context, first *int, after *string, filter *model.EmployeeFilter, sort *model.EmployeeSort) (*model.EmployeeConnection, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	limit := 25
	if first != nil {
		limit = *first
	}
	afterStr := ""
	if after != nil {
		afterStr = *after
	}
	f, err := toServiceFilter(filter)
	if err != nil {
		return nil, err
	}
	page, err := r.EmpSvc.List(ctx, tid, f, gqlSortToService(sort), limit, afterStr)
	if err != nil {
		return nil, err
	}
	return toGQLEmployeeConnection(page), nil
}

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id string) (*model.Employee, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	eID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	e, err := r.EmpSvc.Get(ctx, tid, eID)
	if err != nil {
		return nil, err
	}
	return toGQLEmployee(e), nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func toCreateEmployeeInput(in model.CreateEmployeeInput) (employee.CreateInput, error) {
	joining, err := parseDate(in.JoiningDate)
	if err != nil {
		return employee.CreateInput{}, err
	}
	dob, err := parseDatePtr(in.DateOfBirth)
	if err != nil {
		return employee.CreateInput{}, err
	}
	dept, err := pIDFromStr(in.DepartmentID)
	if err != nil {
		return employee.CreateInput{}, err
	}
	desig, err := pIDFromStr(in.DesignationID)
	if err != nil {
		return employee.CreateInput{}, err
	}
	loc, err := pIDFromStr(in.LocationID)
	if err != nil {
		return employee.CreateInput{}, err
	}
	mgr, err := pIDFromStr(in.ManagerID)
	if err != nil {
		return employee.CreateInput{}, err
	}
	return employee.CreateInput{
		EmployeeCode:   in.EmployeeCode,
		FirstName:      in.FirstName,
		LastName:       in.LastName,
		Email:          in.Email,
		Phone:          in.Phone,
		DateOfBirth:    dob,
		Gender:         in.Gender,
		JoiningDate:    joining,
		EmploymentType: in.EmploymentType,
		DepartmentID:   dept,
		DesignationID:  desig,
		LocationID:     loc,
		ManagerID:      mgr,
	}, nil
}
func toUpdateEmployeeInput(in model.UpdateEmployeeInput) (employee.UpdateInput, error) {
	joining, err := parseDatePtr(in.JoiningDate)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	dob, err := parseDatePtr(in.DateOfBirth)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	dept, err := pIDFromStr(in.DepartmentID)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	desig, err := pIDFromStr(in.DesignationID)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	loc, err := pIDFromStr(in.LocationID)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	mgr, err := pIDFromStr(in.ManagerID)
	if err != nil {
		return employee.UpdateInput{}, err
	}
	return employee.UpdateInput{
		EmployeeCode:   in.EmployeeCode,
		FirstName:      in.FirstName,
		LastName:       in.LastName,
		Email:          in.Email,
		Phone:          in.Phone,
		DateOfBirth:    dob,
		Gender:         in.Gender,
		JoiningDate:    joining,
		EmploymentType: in.EmploymentType,
		DepartmentID:   dept,
		DesignationID:  desig,
		LocationID:     loc,
		ManagerID:      mgr,
		Status:         in.Status,
	}, nil
}
func toServiceFilter(f *model.EmployeeFilter) (employee.Filter, error) {
	if f == nil {
		return employee.Filter{}, nil
	}
	dept, err := pIDFromStr(f.DepartmentID)
	if err != nil {
		return employee.Filter{}, err
	}
	desig, err := pIDFromStr(f.DesignationID)
	if err != nil {
		return employee.Filter{}, err
	}
	loc, err := pIDFromStr(f.LocationID)
	if err != nil {
		return employee.Filter{}, err
	}
	mgr, err := pIDFromStr(f.ManagerID)
	if err != nil {
		return employee.Filter{}, err
	}
	return employee.Filter{
		Search:        f.Search,
		Status:        f.Status,
		DepartmentID:  dept,
		DesignationID: desig,
		LocationID:    loc,
		ManagerID:     mgr,
	}, nil
}
func toGQLEmployeeConnection(p employee.Page) *model.EmployeeConnection {
	edges := make([]*model.EmployeeEdge, 0, len(p.Items))
	for i := range p.Items {
		node := toGQLEmployee(&p.Items[i])
		edges = append(edges, &model.EmployeeEdge{
			Cursor: cursorAt(p, i),
			Node:   node,
		})
	}
	var startC, endC *string
	if p.StartCursor != "" {
		s := p.StartCursor
		startC = &s
	}
	if p.EndCursor != "" {
		s := p.EndCursor
		endC = &s
	}
	return &model.EmployeeConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     p.HasNext,
			HasPreviousPage: p.HasPrev,
			StartCursor:     startC,
			EndCursor:       endC,
		},
		TotalCount: p.TotalCount,
	}
}
func cursorAt(p employee.Page, i int) string {
	if i == 0 && p.StartCursor != "" {
		return p.StartCursor
	}
	if i == len(p.Items)-1 && p.EndCursor != "" {
		return p.EndCursor
	}
	return p.EndCursor
}
