package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/graph/model"
)

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context) ([]*model.Country, error) {
	items, err := r.GeoRepo.ListCountries(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Country, len(items))
	for i := range items {
		out[i] = toGQLCountry(items[i])
	}
	return out, nil
}

// States is the resolver for the states field.
func (r *queryResolver) States(ctx context.Context, countryID string) ([]*model.State, error) {
	cID, err := parseID(countryID)
	if err != nil {
		return nil, err
	}
	items, err := r.GeoRepo.ListStates(ctx, cID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.State, len(items))
	for i := range items {
		out[i] = toGQLState(items[i])
	}
	return out, nil
}

// Cities is the resolver for the cities field.
func (r *queryResolver) Cities(ctx context.Context, stateID string) ([]*model.City, error) {
	sID, err := parseID(stateID)
	if err != nil {
		return nil, err
	}
	items, err := r.GeoRepo.ListCities(ctx, sID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.City, len(items))
	for i := range items {
		out[i] = toGQLCity(items[i])
	}
	return out, nil
}
