package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/graph/model"
	"github.com/sodium-labs/hrms/backend/internal/modules/location"
)

// CreateLocation is the resolver for the createLocation field.
func (r *mutationResolver) CreateLocation(ctx context.Context, input model.CreateLocationInput) (*model.Location, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	cid, err := pIDFromStr(input.CountryID)
	if err != nil {
		return nil, err
	}
	sid, err := pIDFromStr(input.StateID)
	if err != nil {
		return nil, err
	}
	cityID, err := pIDFromStr(input.CityID)
	if err != nil {
		return nil, err
	}
	l, err := r.LocSvc.Create(ctx, tid, location.CreateInput{
		Name:         input.Name,
		AddressLine1: input.AddressLine1,
		AddressLine2: input.AddressLine2,
		CountryID:    cid,
		StateID:      sid,
		CityID:       cityID,
		Pincode:      input.Pincode,
		Timezone:     input.Timezone,
	})
	if err != nil {
		return nil, err
	}
	return toGQLLocation(l), nil
}

// UpdateLocation is the resolver for the updateLocation field.
func (r *mutationResolver) UpdateLocation(ctx context.Context, id string, input model.UpdateLocationInput) (*model.Location, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	lID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	cid, err := pIDFromStr(input.CountryID)
	if err != nil {
		return nil, err
	}
	sid, err := pIDFromStr(input.StateID)
	if err != nil {
		return nil, err
	}
	cityID, err := pIDFromStr(input.CityID)
	if err != nil {
		return nil, err
	}
	l, err := r.LocSvc.Update(ctx, tid, lID, location.UpdateInput{
		Name:         input.Name,
		AddressLine1: input.AddressLine1,
		AddressLine2: input.AddressLine2,
		CountryID:    cid,
		StateID:      sid,
		CityID:       cityID,
		Pincode:      input.Pincode,
		Timezone:     input.Timezone,
		Status:       input.Status,
	})
	if err != nil {
		return nil, err
	}
	return toGQLLocation(l), nil
}

// DeleteLocation is the resolver for the deleteLocation field.
func (r *mutationResolver) DeleteLocation(ctx context.Context, id string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	lID, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.LocSvc.Delete(ctx, tid, lID); err != nil {
		return false, err
	}
	return true, nil
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context) ([]*model.Location, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.LocSvc.List(ctx, tid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Location, len(items))
	for i := range items {
		out[i] = toGQLLocation(&items[i])
	}
	return out, nil
}

// Location is the resolver for the location field.
func (r *queryResolver) Location(ctx context.Context, id string) (*model.Location, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	lID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	l, err := r.LocSvc.Get(ctx, tid, lID)
	if err != nil {
		return nil, err
	}
	return toGQLLocation(l), nil
}
