package resolver

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require here.

import (
	"github.com/sodium-labs/hrms/backend/internal/modules/department"
	"github.com/sodium-labs/hrms/backend/internal/modules/designation"
	"github.com/sodium-labs/hrms/backend/internal/modules/employee"
	"github.com/sodium-labs/hrms/backend/internal/modules/geography"
	"github.com/sodium-labs/hrms/backend/internal/modules/location"
)

// Resolver carries the per-module services that GraphQL fields delegate to.
// Constructed once at startup in cmd/server/main.go and shared across requests
// (services are stateless wrappers over a *pgxpool.Pool).
//
// Field names are deliberately suffixed (e.g. `DeptSvc`, not `Department`) so
// they don't collide with same-named methods generated by gqlgen on the
// embedded resolver structs (`queryResolver.Department(ctx, id) (*Department,
// error)`).
type Resolver struct {
	DeptSvc  *department.Service
	DesigSvc *designation.Service
	LocSvc   *location.Service
	EmpSvc   *employee.Service
	GeoRepo  *geography.Repo
}
