package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/sodium-labs/hrms/backend/internal/auth"
	"github.com/sodium-labs/hrms/backend/internal/graph/model"
	"github.com/sodium-labs/hrms/backend/internal/modules/role"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input model.CreateRoleInput) (*model.Role, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	permIDs, err := parseIDs(input.PermissionIds)
	if err != nil {
		return nil, err
	}
	ro, err := r.RoleSvc.Create(ctx, tid, role.CreateInput{
		Name:          input.Name,
		Description:   input.Description,
		PermissionIDs: permIDs,
	})
	if err != nil {
		return nil, err
	}
	return toGQLRole(ro), nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, input model.UpdateRoleInput) (*model.Role, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	rID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	ro, err := r.RoleSvc.Update(ctx, tid, rID, role.UpdateInput{
		Name:        input.Name,
		Description: input.Description,
		Status:      input.Status,
	})
	if err != nil {
		return nil, err
	}
	return toGQLRole(ro), nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	rID, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.RoleSvc.Delete(ctx, tid, rID); err != nil {
		return false, err
	}
	return true, nil
}

// SetRolePermissions is the resolver for the setRolePermissions field.
func (r *mutationResolver) SetRolePermissions(ctx context.Context, roleID string, permissionIds []string) (*model.Role, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	rID, err := parseID(roleID)
	if err != nil {
		return nil, err
	}
	permIDs, err := parseIDs(permissionIds)
	if err != nil {
		return nil, err
	}
	ro, err := r.RoleSvc.SetPermissions(ctx, tid, rID, permIDs)
	if err != nil {
		return nil, err
	}
	return toGQLRole(ro), nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID string, roleID string) (bool, error) {
	uID, err := parseID(userID)
	if err != nil {
		return false, err
	}
	rID, err := parseID(roleID)
	if err != nil {
		return false, err
	}
	if err := r.RoleSvc.AssignUser(ctx, uID, rID); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, roleID string) (bool, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return false, err
	}
	p, ok := auth.FromContext(ctx)
	if !ok {
		return false, errNoTenant
	}
	uID, err := parseID(userID)
	if err != nil {
		return false, err
	}
	rID, err := parseID(roleID)
	if err != nil {
		return false, err
	}
	if err := r.RoleSvc.RevokeUser(ctx, tid, p.UserID, uID, rID); err != nil {
		return false, err
	}
	return true, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.RoleSvc.List(ctx, tid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Role, len(items))
	for i := range items {
		out[i] = toGQLRole(&items[i])
	}
	return out, nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	rID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	ro, err := r.RoleSvc.Get(ctx, tid, rID)
	if err != nil {
		return nil, err
	}
	return toGQLRole(ro), nil
}

// AllPermissions is the resolver for the allPermissions field.
func (r *queryResolver) AllPermissions(ctx context.Context) ([]*model.RolePermission, error) {
	items, err := r.RoleSvc.ListPermissions(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.RolePermission, len(items))
	for i := range items {
		out[i] = toGQLPermission(&items[i])
	}
	return out, nil
}

// UserRoles is the resolver for the userRoles field.
func (r *queryResolver) UserRoles(ctx context.Context, userID string) ([]*model.UserRole, error) {
	uID, err := parseID(userID)
	if err != nil {
		return nil, err
	}
	items, err := r.RoleSvc.UserRoles(ctx, uID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.UserRole, len(items))
	for i := range items {
		out[i] = &model.UserRole{
			UserID:   idStr(items[i].UserID),
			RoleID:   idStr(items[i].RoleID),
			RoleName: items[i].RoleName,
		}
	}
	return out, nil
}

// UsersWithRole is the resolver for the usersWithRole field.
func (r *queryResolver) UsersWithRole(ctx context.Context, roleID string) ([]*model.RoleUser, error) {
	tid, err := tenantOf(ctx)
	if err != nil {
		return nil, err
	}
	rID, err := parseID(roleID)
	if err != nil {
		return nil, err
	}
	items, err := r.RoleSvc.UsersWithRole(ctx, tid, rID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.RoleUser, len(items))
	for i := range items {
		out[i] = &model.RoleUser{
			UserID: idStr(items[i].UserID),
			Email:  items[i].Email,
		}
	}
	return out, nil
}
