package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"strconv"

	"github.com/sodium-labs/hrms/backend/internal/auth"
	"github.com/sodium-labs/hrms/backend/internal/graph/generated"
	"github.com/sodium-labs/hrms/backend/internal/graph/model"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.Viewer, error) {
	p, ok := auth.FromContext(ctx)
	if !ok {
		return nil, nil
	}
	perms := make([]string, 0, len(p.Perms))
	for k := range p.Perms {
		perms = append(perms, k)
	}
	return &model.Viewer{
		UserID:      strconv.FormatInt(p.UserID, 10),
		TenantID:    strconv.FormatInt(p.TenantID, 10),
		Permissions: perms,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
