// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type City struct {
	ID      string  `json:"id"`
	StateID *string `json:"stateId,omitempty"`
	Name    string  `json:"name"`
}

// Read-only geography catalog. Used to drive country → state → city dropdowns
// on location and employee forms. Rows are tenant-agnostic seed data; mutations
// are migration-only.
type Country struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	IsoCode *string `json:"isoCode,omitempty"`
}

type CreateDepartmentInput struct {
	Name     string  `json:"name"`
	Code     *string `json:"code,omitempty"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreateDesignationInput struct {
	Title        string  `json:"title"`
	Level        *int    `json:"level,omitempty"`
	DepartmentID *string `json:"departmentId,omitempty"`
}

type CreateEmployeeInput struct {
	EmployeeCode   string  `json:"employeeCode"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	JoiningDate    string  `json:"joiningDate"`
	EmploymentType *string `json:"employmentType,omitempty"`
	DepartmentID   *string `json:"departmentId,omitempty"`
	DesignationID  *string `json:"designationId,omitempty"`
	LocationID     *string `json:"locationId,omitempty"`
	ManagerID      *string `json:"managerId,omitempty"`
}

type CreateLocationInput struct {
	Name         string  `json:"name"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	CountryID    *string `json:"countryId,omitempty"`
	StateID      *string `json:"stateId,omitempty"`
	CityID       *string `json:"cityId,omitempty"`
	Pincode      *string `json:"pincode,omitempty"`
	Timezone     *string `json:"timezone,omitempty"`
}

// Department in the org tree. `parentId` may be null for root nodes; the
// service rejects parent assignments that would close a cycle.
type Department struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Code      *string `json:"code,omitempty"`
	ParentID  *string `json:"parentId,omitempty"`
	Status    string  `json:"status"`
	CreatedAt int     `json:"createdAt"`
	UpdatedAt int     `json:"updatedAt"`
}

// Job titles within a tenant, optionally bucketed under a department and a
// seniority level (free-form integer; the meaning is per-tenant).
type Designation struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	Level        *int    `json:"level,omitempty"`
	DepartmentID *string `json:"departmentId,omitempty"`
	Status       string  `json:"status"`
	CreatedAt    int     `json:"createdAt"`
	UpdatedAt    int     `json:"updatedAt"`
}

// Employee record. Dates (`dateOfBirth`, `joiningDate`) are ISO yyyy-mm-dd
// strings; timestamps (`createdAt`, `updatedAt`) are unix seconds. The four
// FK ids resolve via the corresponding Department/Designation/Location/
// Employee types — fetched per-row today, dataloader batching tracked under
// plan §7.
type Employee struct {
	ID             string  `json:"id"`
	EmployeeCode   string  `json:"employeeCode"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	JoiningDate    string  `json:"joiningDate"`
	EmploymentType *string `json:"employmentType,omitempty"`
	DepartmentID   *string `json:"departmentId,omitempty"`
	DesignationID  *string `json:"designationId,omitempty"`
	LocationID     *string `json:"locationId,omitempty"`
	ManagerID      *string `json:"managerId,omitempty"`
	Status         string  `json:"status"`
	CreatedAt      int     `json:"createdAt"`
	UpdatedAt      int     `json:"updatedAt"`
}

type EmployeeConnection struct {
	Edges      []*EmployeeEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type EmployeeEdge struct {
	Cursor string    `json:"cursor"`
	Node   *Employee `json:"node"`
}

type EmployeeFilter struct {
	Search        *string `json:"search,omitempty"`
	Status        *string `json:"status,omitempty"`
	DepartmentID  *string `json:"departmentId,omitempty"`
	DesignationID *string `json:"designationId,omitempty"`
	LocationID    *string `json:"locationId,omitempty"`
	ManagerID     *string `json:"managerId,omitempty"`
}

// A physical office or hub. The `timezone` is an IANA tz name (e.g.
// "Asia/Kolkata"); timestamps elsewhere remain UTC and are converted to this
// timezone on the client at render time only.
type Location struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	CountryID    *string `json:"countryId,omitempty"`
	StateID      *string `json:"stateId,omitempty"`
	CityID       *string `json:"cityId,omitempty"`
	Pincode      *string `json:"pincode,omitempty"`
	Timezone     *string `json:"timezone,omitempty"`
	Status       string  `json:"status"`
	CreatedAt    int     `json:"createdAt"`
	UpdatedAt    int     `json:"updatedAt"`
}

// Root Mutation type. Per-domain mutation fields land here via `extend type
// Mutation` in their own schema files.
type Mutation struct {
}

// Relay-style PageInfo. `hasPreviousPage` is true whenever the request
// included an `after` cursor — we don't yet support backward pagination, so
// this is a coarse approximation, sufficient for "show prev" buttons.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type State struct {
	ID        string  `json:"id"`
	CountryID *string `json:"countryId,omitempty"`
	Name      string  `json:"name"`
}

type UpdateDepartmentInput struct {
	Name     *string `json:"name,omitempty"`
	Code     *string `json:"code,omitempty"`
	ParentID *string `json:"parentId,omitempty"`
	Status   *string `json:"status,omitempty"`
}

type UpdateDesignationInput struct {
	Title        *string `json:"title,omitempty"`
	Level        *int    `json:"level,omitempty"`
	DepartmentID *string `json:"departmentId,omitempty"`
	Status       *string `json:"status,omitempty"`
}

type UpdateEmployeeInput struct {
	EmployeeCode   *string `json:"employeeCode,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	JoiningDate    *string `json:"joiningDate,omitempty"`
	EmploymentType *string `json:"employmentType,omitempty"`
	DepartmentID   *string `json:"departmentId,omitempty"`
	DesignationID  *string `json:"designationId,omitempty"`
	LocationID     *string `json:"locationId,omitempty"`
	ManagerID      *string `json:"managerId,omitempty"`
	Status         *string `json:"status,omitempty"`
}

type UpdateLocationInput struct {
	Name         *string `json:"name,omitempty"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	CountryID    *string `json:"countryId,omitempty"`
	StateID      *string `json:"stateId,omitempty"`
	CityID       *string `json:"cityId,omitempty"`
	Pincode      *string `json:"pincode,omitempty"`
	Timezone     *string `json:"timezone,omitempty"`
	Status       *string `json:"status,omitempty"`
}

// Viewer is the authenticated caller projected from the JWT principal.
// This is the M1 smoke-test surface — proves auth + tenant + RBAC plumbing
// are wired end-to-end before the per-domain schemas land.
type Viewer struct {
	UserID      string   `json:"userId"`
	TenantID    string   `json:"tenantId"`
	Permissions []string `json:"permissions"`
}

type EmployeeSort string

const (
	EmployeeSortCreatedDesc EmployeeSort = "CREATED_DESC"
	EmployeeSortCreatedAsc  EmployeeSort = "CREATED_ASC"
	EmployeeSortNameAsc     EmployeeSort = "NAME_ASC"
	EmployeeSortNameDesc    EmployeeSort = "NAME_DESC"
	EmployeeSortJoiningDesc EmployeeSort = "JOINING_DESC"
	EmployeeSortJoiningAsc  EmployeeSort = "JOINING_ASC"
)

var AllEmployeeSort = []EmployeeSort{
	EmployeeSortCreatedDesc,
	EmployeeSortCreatedAsc,
	EmployeeSortNameAsc,
	EmployeeSortNameDesc,
	EmployeeSortJoiningDesc,
	EmployeeSortJoiningAsc,
}

func (e EmployeeSort) IsValid() bool {
	switch e {
	case EmployeeSortCreatedDesc, EmployeeSortCreatedAsc, EmployeeSortNameAsc, EmployeeSortNameDesc, EmployeeSortJoiningDesc, EmployeeSortJoiningAsc:
		return true
	}
	return false
}

func (e EmployeeSort) String() string {
	return string(e)
}

func (e *EmployeeSort) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmployeeSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmployeeSort", str)
	}
	return nil
}

func (e EmployeeSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
