// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthUser struct {
	UserID    uint64  `json:"userId"`
	TenantID  uint64  `json:"tenantId"`
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     *string `json:"phone,omitempty"`
}

type City struct {
	ID      uint64  `json:"id"`
	StateID uint64  `json:"stateId"`
	State   *State  `json:"state"`
	Name    string  `json:"name"`
	Code    *string `json:"code,omitempty"`
	Status  string  `json:"status"`
}

type Country struct {
	ID                  uint64   `json:"id"`
	Code                string   `json:"code"`
	Name                string   `json:"name"`
	IsoCode             *string  `json:"isoCode,omitempty"`
	CurrencyCode        string   `json:"currencyCode"`
	CurrencySymbol      *string  `json:"currencySymbol,omitempty"`
	PhoneCode           *string  `json:"phoneCode,omitempty"`
	Timezone            *string  `json:"timezone,omitempty"`
	DateFormat          string   `json:"dateFormat"`
	FiscalYearStart     string   `json:"fiscalYearStart"`
	WorkingHoursPerWeek float64  `json:"workingHoursPerWeek"`
	Status              string   `json:"status"`
	States              []*State `json:"states,omitempty"`
}

type CreateCityInput struct {
	StateID uint64  `json:"stateId"`
	Name    string  `json:"name"`
	Code    *string `json:"code,omitempty"`
}

type CreateCountryInput struct {
	Code                string   `json:"code"`
	Name                string   `json:"name"`
	IsoCode             *string  `json:"isoCode,omitempty"`
	CurrencyCode        string   `json:"currencyCode"`
	CurrencySymbol      *string  `json:"currencySymbol,omitempty"`
	PhoneCode           *string  `json:"phoneCode,omitempty"`
	Timezone            *string  `json:"timezone,omitempty"`
	DateFormat          *string  `json:"dateFormat,omitempty"`
	FiscalYearStart     *string  `json:"fiscalYearStart,omitempty"`
	WorkingHoursPerWeek *float64 `json:"workingHoursPerWeek,omitempty"`
}

type CreateDepartment struct {
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateDesignation struct {
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Level       *int32  `json:"level,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateLocation struct {
	TenantID       string  `json:"tenantId"`
	Name           string  `json:"name"`
	Code           *string `json:"code,omitempty"`
	Address        *string `json:"address,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	Email          *string `json:"email,omitempty"`
	Timezone       *string `json:"timezone,omitempty"`
	IsHeadquarters *bool   `json:"isHeadquarters,omitempty"`
}

type CreateStateInput struct {
	CountryID uint64  `json:"countryId"`
	Name      string  `json:"name"`
	Code      *string `json:"code,omitempty"`
}

type CreateTenantInput struct {
	Name               string  `json:"name"`
	Code               string  `json:"code"`
	LegalName          *string `json:"legalName,omitempty"`
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
	TaxID              *string `json:"taxId,omitempty"`
	CountryID          *int32  `json:"countryId,omitempty"`
	CityID             *int32  `json:"cityId,omitempty"`
	PrimaryCurrency    *string `json:"primaryCurrency,omitempty"`
	Timezone           *string `json:"timezone,omitempty"`
	DateFormat         *string `json:"dateFormat,omitempty"`
	FiscalYearStart    *string `json:"fiscalYearStart,omitempty"`
	LogoURL            *string `json:"logoUrl,omitempty"`
	Website            *string `json:"website,omitempty"`
	Email              *string `json:"email,omitempty"`
	Phone              *string `json:"phone,omitempty"`
	Address            *string `json:"address,omitempty"`
	Settings           *string `json:"settings,omitempty"`
}

type Department struct {
	ID          uint64  `json:"id"`
	TenantID    uint64  `json:"tenantId"`
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
}

type Designation struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenantId"`
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Level       *int32  `json:"level,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
}

type Location struct {
	ID             string  `json:"id"`
	TenantID       string  `json:"tenantId"`
	Name           string  `json:"name"`
	Code           *string `json:"code,omitempty"`
	Address        *string `json:"address,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	Email          *string `json:"email,omitempty"`
	Timezone       *string `json:"timezone,omitempty"`
	IsHeadquarters bool    `json:"isHeadquarters"`
	Status         string  `json:"status"`
}

type Login struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	AccessExp    string `json:"accessExp"`
	RefreshExp   string `json:"refreshExp"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type State struct {
	ID        uint64   `json:"id"`
	CountryID uint64   `json:"countryId"`
	Country   *Country `json:"country"`
	Name      string   `json:"name"`
	Code      *string  `json:"code,omitempty"`
	Status    string   `json:"status"`
	Cities    []*City  `json:"cities,omitempty"`
}

type Tenant struct {
	ID                 string  `json:"id"`
	CreatedAt          string  `json:"createdAt"`
	UpdatedAt          string  `json:"updatedAt"`
	Status             string  `json:"status"`
	Name               string  `json:"name"`
	Code               string  `json:"code"`
	LegalName          *string `json:"legalName,omitempty"`
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
	TaxID              *string `json:"taxId,omitempty"`
	CountryID          *int32  `json:"countryId,omitempty"`
	CityID             *int32  `json:"cityId,omitempty"`
	PrimaryCurrency    string  `json:"primaryCurrency"`
	Timezone           string  `json:"timezone"`
	DateFormat         string  `json:"dateFormat"`
	FiscalYearStart    string  `json:"fiscalYearStart"`
	LogoURL            *string `json:"logoUrl,omitempty"`
	Website            *string `json:"website,omitempty"`
	Email              *string `json:"email,omitempty"`
	Phone              *string `json:"phone,omitempty"`
	Address            *string `json:"address,omitempty"`
	Settings           *string `json:"settings,omitempty"`
}
