// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateDepartment struct {
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateDesignation struct {
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Level       *int32  `json:"level,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateLocation struct {
	TenantID       string  `json:"tenantId"`
	Name           string  `json:"name"`
	Code           *string `json:"code,omitempty"`
	Address        *string `json:"address,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	Email          *string `json:"email,omitempty"`
	Timezone       *string `json:"timezone,omitempty"`
	IsHeadquarters *bool   `json:"isHeadquarters,omitempty"`
}

type Department struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenantId"`
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
}

type Designation struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenantId"`
	Name        string  `json:"name"`
	Code        *string `json:"code,omitempty"`
	Level       *int32  `json:"level,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
}

type Location struct {
	ID             string  `json:"id"`
	TenantID       string  `json:"tenantId"`
	Name           string  `json:"name"`
	Code           *string `json:"code,omitempty"`
	Address        *string `json:"address,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	Email          *string `json:"email,omitempty"`
	Timezone       *string `json:"timezone,omitempty"`
	IsHeadquarters bool    `json:"isHeadquarters"`
	Status         string  `json:"status"`
}

type Mutation struct {
}

type Query struct {
}
