package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"

	"github.com/pawan13g/hrms/graph/model"
)

// Me is the resolver for the me field.
func (r *mutationResolver) Me(ctx context.Context) (*model.AuthUser, error) {
	raw := ctx.Value("authorization").(string)
	if !strings.HasPrefix(raw, "Bearer ") {
		return nil, fmt.Errorf("invalid authorization header")
	}

	return r.AuthService.GetSession(raw[len("Bearer "):])
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.Login, error) {
	session, err := r.AuthService.Login(input)
	if err != nil {
		return nil, err
	}
	return session, nil
}
