package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/pawan13g/hrms/graph/model"
)

// CreateDesignation is the resolver for the createDesignation field.
func (r *mutationResolver) CreateDesignation(ctx context.Context, input model.CreateDesignation) (*model.Designation, error) {
	panic(fmt.Errorf("not implemented: CreateDesignation - createDesignation"))
}

// Designations is the resolver for the designations field.
func (r *queryResolver) Designations(ctx context.Context, tenantID string) ([]*model.Designation, error) {
	panic(fmt.Errorf("not implemented: Designations - designations"))
}
