package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/pawan_13g/hrms/graph/model"
)

// CreateLocation is the resolver for the createLocation field.
func (r *mutationResolver) CreateLocation(ctx context.Context, input model.CreateLocation) (*model.Location, error) {
	panic(fmt.Errorf("not implemented: CreateLocation - createLocation"))
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context, tenantID string) ([]*model.Location, error) {
	panic(fmt.Errorf("not implemented: Locations - locations"))
}
