package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/pawan13g/hrms/graph/model"
)

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input model.CreateTenantInput) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: CreateTenant - createTenant"))
}

// GetTenantByID is the resolver for the getTenantById field.
func (r *queryResolver) GetTenantByID(ctx context.Context, tenantID string) ([]*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: GetTenantByID - getTenantById"))
}

// GetTenents is the resolver for the getTenents field.
func (r *queryResolver) GetTenents(ctx context.Context) ([]*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: GetTenents - getTenents"))
}
